version: '2.3'

services:

  unifi:
    image: stlouisn/unifi
    container_name: unifi
    restart: always
    volumes:
      - ./unifi/config:/usr/lib/unifi/data:rw
    depends_on:
      - mongo
    links:
      - mongo:mongo
    ports:
      - 8080
      - 8043
      - 8843
      - 8880

 mongo:
    image: library/mongo
    container_name: mongo
    command:
      - '--smallfiles'
      - '--storageEngine'
      - 'wiredTiger'
    restart: always
    volumes:
      - ./mongo/config:/data/configdb:rw
      - ./mongo/data:/data/db:rw
    expose:
      - 27017
