version: '2.3'

services:

  unifi:
    image: stlouisn/unifi:stable
    container_name: unifi
    hostname: unifi
    environment:
      - TZ=UTC
    restart: always
    volumes:
      - /docker/unifi/config:/usr/lib/unifi/data:rw
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mongo
    links:
      - mongo:mongo
    ports:
      - 8080
      - 8043
      - 8843
      - 8880

 mongo:
    image: library/mongo
    container_name: mongo
    hostname: mongo
    environment:
      - TZ=UTC
    command:
      - '--smallfiles'
      - '--storageEngine'
      - 'wiredTiger'
      - '--bind_ip_all'
    restart: always
    volumes:
      - /docker/mongo/config:/data/configdb:rw
      - /docker/mongo/data:/data/db:rw
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    expose:
      - 27017
